#
# Manifest to create MySQL cluster based on an existing cluster called mysql-01
#
# This will use the backup of the source cluster closest to the "timestamp" specificed
# in the basedOn: section of the manifest
#
apiVersion: databases.dataservices.vmware.com/v1alpha1
kind: MySQLCluster
metadata:
  annotations:
    dsm.vmware.com/owner: provider@broadcom.com
  name: mysql-restore-02
  namespace: default
spec:
  backupConfig:
    backupRetentionDays: 30
    schedules:
    - name: default-full-backup
      schedule: 59 23 * * 6
      type: full
  backupLocation:
    name: dsm2-db-backup
  infrastructurePolicy:
    name: infra-policy-01
  maintenanceWindow:
    duration: 6h0m0s
    startDay: SATURDAY
    startTime: "23:59"
  members: 1
  storagePolicyName: vSAN Default Storage Policy
  storageSpace: 60Gi
  version: 8.0.29+vmware.v2.0.0-rc.8
  vmClass:
    name: medium
  basedOn:
    cluster:
      name: mysql-01
      timestamp: "2024-01-17T15:10:00Z"
