#
# Sample manifest to create a single node PostgreSQL database
# using the DSM Gateway API
#
# You may need to modify the following field:
# - owner
# - backupLocation.name
# - infrastructurePolocy
# - storagePolicyName
#
# This can only be run using the kubeconfig from the DSM appliance.
# It cannot be run using the kubeconfig from the vSphere Client.
#
apiVersion: databases.dataservices.vmware.com/v1alpha1
kind: PostgresCluster
metadata:
  annotations:
    dsm.vmware.com/owner: provider@broadcom.com
  name: pg-02
  namespace: default
spec:
  adminUsername: pgadmin
  backupConfig:
    backupRetentionDays: 30
    schedules:
    - name: default-full-backup
      schedule: 59 23 * * 6
      type: full
    - name: default-incremental-backup
      schedule: 59 23 1/1 * *
      type: incremental
  backupLocation:
    name: dsm2-db-backup
  databaseName: pg-02
  infrastructurePolicy:
    name: infra-policy-01
  maintenanceWindow:
    duration: 6h0m0s
    startDay: SATURDAY
    startTime: "23:59"
  replicas: 0
  storagePolicyName: vSAN Default Storage Policy
  storageSpace: 60Gi
  version: 15.5+vmware.v2.0.0-rc.8
  vmClass:
    name: medium
