#
# Sample manifest to create a single node PostgreSQL database server
# using the DSM Gateway API
#
# The infrastructure policy chosen contains 2 x vSphere Clusters. 
# However, this manifest controls the placement onto Cluster-A
# and does not let DSM make the placement decision 
#
# You may need to modify the following fields in your deployment:
# - owner
# - backupLocation
# - infrastructurePolocy
# - storagePolicyName
# - placementSelector
#
# This manifest can only be run using the kubeconfig from the DSM appliance as DSM user.
# It cannot be run using the kubeconfig from the vSphere Client (as infrastrucutre admin).
#
apiVersion: databases.dataservices.vmware.com/v1alpha1
kind: PostgresCluster
metadata:
  annotations:
    dsm.vmware.com/owner: provider@broadcom.com
  name: placement-pg-01
  namespace: default
spec:
  adminUsername: pgadmin
  backupConfig:
    backupRetentionDays: 30
    schedules:
    - name: default-full-backup
      schedule: 59 23 * * 6
      type: full
    - name: default-incremental-backup
      schedule: 59 23 1/1 * *
      type: incremental
  backupLocation:
    name: dsm2-db-backup
  databaseName: placement-pg-01
  infrastructurePolicy:
    name: infra-policy-01
  maintenanceWindow:
    duration: 6h0m0s
    startDay: SATURDAY
    startTime: "23:59"
  placementSelector:
    cluster: Cluster-A
    datacenter: /OCTO-Datacenter
  replicas: 0
  storagePolicyName: vSAN Default Storage Policy
  storageSpace: 60Gi
  version: 12.17+vmware.v2.0.0-rc.8
  vmClass:
    name: medium
