#
# Manifest for an infrastructure policy which uses two vSphere clusters compute resources
# using the DSM Gateway API as Infra Admin
#
# You may need to make some changes for this to work on your own infrastructure
#
apiVersion: infrastructure.dataservices.vmware.com/v1alpha1
kind: InfrastructurePolicy
metadata:
  name: infra-policy-01
spec:
  enabled: true
  ipRanges:
  - poolName: ip-pool-0
    portGroups:
    - datacenter: /OCTO-Datacenter
      name: VM-51-DPG-B
    - datacenter: /OCTO-Datacenter
      name: VM-51-DPG
  placements:
  - cluster: Cluster-B
    datacenter: /OCTO-Datacenter
    folder: DB
    portGroups:
    - VM-51-DPG-B
  - cluster: Cluster-A
    datacenter: /OCTO-Datacenter
    folder: DB
    portGroups:
    - VM-51-DPG
  storagePolicies:
  - vSAN Default Storage Policy
  vmClasses:
  - name: medium
