#
# Manifest for an infrastructure policy which uses a single vSphere cluster compute resources
# using the DSM Gateway API as Infra Admin
#
# You may need to make some changes for this to work on your own infrastructure
#
apiVersion: infrastructure.dataservices.vmware.com/v1alpha1
kind: InfrastructurePolicy
metadata:
  name: infra-policy-02
spec:
  enabled: false
  ipRanges:
  - poolName: ip-pool-1
    portGroups:
    - datacenter: /OCTO-Datacenter
      name: VM-51-DPG-B
    - datacenter: /OCTO-Datacenter
      name: VM-51-DPG
  placements:
  - cluster: Cluster-A
    datacenter: /OCTO-Datacenter
    folder: DB
    portGroups:
    - VM-70-DPG
  storagePolicies:
  - vSAN Default Storage Policy
  vmClasses:
  - name: x-large
